### ISSUE TITLE
Fix breadcrumbs

### ISSUE THREAD

**Issue by paddycarver** [iron-io/docs#56]
Right now, breadcrumbs handling is pretty dumb. It'd be nice to update it so that we weren't dependent on YAML arrays and could actually do something like:

``` yaml
breadcrumbs:
  - slug: /articles
    title: "Articles"
  - slug: /data
    title: "Working With Data &amp; Databases"
```
